### ISSUE TITLE
How to color by individual

### ISSUE THREAD

**Issue by caggtaagtat** [veg/hivtrace-viz#73]
Hi, 
We would like to monitor infections across individuals. Therefore, we would like to color the individuals by their ID. How can I intregrate this information. I tried loading it as a CSV file in your webprogramm, but that didn't work. In another issue, you said, that the json file has to already have the information. But how can I get this information into the json file? hivtrace seems to have no command for that, that I found.

**Comment by spond** [comment]
Dear @caggtaagtat,

See Issue #72 for some related discussions (`hivnetworkannotate`). Assigning unique colors to each node in a network with 20+ individuals is going to be challenging because we (humans) are simply not that good at telling similar colors apart unless they are right next to each other. For that reason `hivtrace-viz` only displays up to 36 different values as colors.

I would suggest that you simply display node IDs using the menu item in the `Clusters` pull-down.

Best,
Sergei

<img width="247" alt="Screen Shot 2020-08-19 at 2 27 26 PM" src="https://user-images.githubusercontent.com/1018513/90675189-2117d280-e228-11ea-8fb8-497d550c40d6.png">

**Comment by caggtaagtat** [comment]
Thank you for the fast reply. I will just use the IDs then
